### ISSUE TITLE
Reuse of the list library

### ISSUE THREAD

**Issue by ankitdaf** [tuanpmt/esp-request#2]
The files list.c and list.h are conflicting the include of the list library from the esp-idf sdk.
This means that if you use esp-request (wifi) along with blueooth, you'll get tonnes of multiple definition errors. 

It's hacky, but I fixed it by renaming every reference to list as tuanslist .

Any chance you can work on this to fix it cleanly ?

**Comment by tuanpmt** [comment]
i will check their list library before rename it. Thanks
