### ISSUE TITLE
Protocol is required error

### ISSUE THREAD

**Issue by peterdeka** [tuanpmt/esp-request#6]
Hi you have a bug in the `req_setopt` function when setting `REQ_SET_PROTOCOL` as passing and enum as argument, will make the `if(!req || !data)` condition evaluate to `false` and the function to return not setting the protocol.
In any case also upon the creation of a new request with `req_new`, seems that the request has not the protocol set and any perform will fail with the protocol error.

**Comment by peterdeka** [comment]
Hi this solves the problem when explicitly setting the protocol via the `set_opt` function, but upon creating a new request the problem is still there!

Pietro

**Comment by tuanpmt** [comment]
Thanks
I forgot to put the HTTP protocol into the default
